// Copyright 2023 David Reid

// WARNING: This file has automatically been generated on Wed, 05 Feb 2025 11:14:05 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "pkg/miniaudio/miniaudio.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

