// Copyright 2023 David Reid

// WARNING: This file has automatically been generated on Wed, 05 Feb 2025 11:14:05 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package miniaudioarm64

/*
#cgo linux LDFLAGS: -lpthread -lm -ldl
#include "pkg/miniaudio/miniaudio.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()
