// Copyright 2023 David Reid

// WARNING: This file has automatically been generated on Wed, 05 Feb 2025 11:14:05 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package miniaudio provides Go bindings for libminiaudio.
*/
package miniaudioarm64
