name: Build and Release miniaudio dylibs

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            name: linux
            target: linux
            arch: x86_64
            abi: amd64
          - os: ubuntu-latest
            name: linux
            target: linux
            arch: aarch64
            abi: arm64
          # macOS
          - os: macos-latest
            name: darwin
            target: macos
            arch: x86_64
            abi: amd64
          - os: macos-latest
            name: darwin
            target: macos
            arch: aarch64
            abi: arm64
          # Windows
          - os: windows-latest
            name: windows
            target: windows
            arch: x86_64
            abi: amd64
          - os: windows-latest
            name: windows
            target: windows
            arch: aarch64
            abi: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Show Zig version
        run: zig version

      - name: Build with zig cc (${{ matrix.os }}/${ { matrix.arch } })
        run: |
          make CC="zig cc -target ${{ matrix.arch }}-${{ matrix.target }}" \
               CXX="zig c++ -target ${{ matrix.arch }}-${{ matrix.target }}" \
               AR="zig ar" RANLIB="zig ranlib" build-${{ matrix.name }}-${{ matrix.abi }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libminiaudio-${{ matrix.abi }}
          path: build/libminiaudio-*-${{ matrix.name }}-${{ matrix.abi }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: release

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: release/**/*.dylib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
